#Inspired by: https://medium.com/kinandcartacreated/setup-a-flutter-ci-cd-with-gitlab-ci-part-1-8d40b7a3b3dc

image: fischerscode/flutter:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - lint
  - build
  - deploy

flutter_test:
  stage: test
  script:
    - cd counter_test
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

flutter_lint:
  stage: lint
  script:
    - cd counter_test
    - flutter analyze
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

# flutter_build_android:
#   stage: build
#   before_script:
#     - cd counter_test
#     - flutter packages get
#   script:
#     - flutter build apk --release
#   artifacts:
#     paths:
#       - counter_test/build/app/outputs/apk/release/app-release.apk
  # rules:
  #   - if: $CI_COMMIT_BRANCH != "main"

flutter_build_web:
  stage: build
  before_script:
    - cd counter_test
    - flutter packages get
  script:
    - flutter build web --release
  artifacts:
    paths:
      - counter_test/build/web/*
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

pages:
  stage: deploy
  before_script:
    - cd counter_test
    - flutter packages get
  script:
    - flutter build web --release
    - cp -r build/web ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"